name: "debug_evals"
ckpt_dir: /is/cluster/fast/pmayilvahanan/lm_logs/lingua/llama_76M_d_256_l_12_c4_1.5BT/checkpoints/0000002900/
dump_dir: /is/cluster/fast/pmayilvahanan/lm_logs/lingua/llama_76M_d_256_l_12_c4_1.5BT/checkpoints/0000002900/
metric_log_dir: /is/cluster/fast/pmayilvahanan/lm_logs/lingua/llama_76M_d_256_l_12_c4_1.5BT/
generator:
  max_tokens: 16384
  dtype: bf16
  temperature: 1.0
harness:
  compute_loss: true
  tasks:
    - hellaswag
validation:
  use_val_from_train_src: false
  max_steps: 1000
  root_dir: /fast/smallick/datasets/
  sources:
    - c4_shuffled
    - pile_uc_shuffled
