# Template config, need to change dump_dir, data.root_dir and data.tokenizer.path

# dump_dir: !!CHANGETHIS!!
dump_dir: /home/aiops/zhuty/lingua/outputs/llama2-1b
name: "llama2-1b"
steps: 30000
probe_freq: null
seed: 777

#dynamic_mask: true
#intradoc_mask: true

grad_acc_steps: 16

optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
    fsdp_type: full_shard
    compile: true
    model_dtype: bf16
    matmul_allow_tf32: false
    selective_activation_checkpointing: false
    tp_size: 1

model:
  dim: 2048
  n_layers: 25
  n_heads: 16


data:
    root_dir: /home/aiops/zhuty/lingua/data/
    sources:
        fineweb_edu_10bt_shuffled: 1.0
    batch_size: 1
    prefetch_size: 1024
    seq_len: 8192
    n_views: 2
    load_async: true
    tokenizer:
        name: sp
        path: /home/aiops/zhuty/lingua/llama2_tokenizer/tokenizer.model
    add_bos: true
    add_eos: true

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 2500
    keep: 3
  eval:
    every: 5000
    keep: -1


logging:
    freq: 1
    wandb:
        project: 'linguatrain'

eval:
    generator:
        max_tokens: 8192
        dtype: bf16
#        temperature: 1.0
#        top_p: 0.95
    harness:
        tasks:
            - hellaswag
#            - piqa
#            - task: nq_open
#              num_fewshot: 5
    validation:
        max_steps: 1000
