# Template config, need to change dump_dir, data.root_dir and tokenizer.path
# param-count: 75,897,088
dump_dir: /is/cluster/fast/pmayilvahanan/lm_logs/lingua/llama_76M_d_256_l_12_c4_1.5BT/
name: llama_76M
steps: 2_900
probe_freq: null
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  dim: 256
  n_layers: 12
  n_heads: 8

data:
  root_dir: /fast/smallick/datasets/
  sources:
      c4_shuffled: 1.0
  batch_size: 32
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: tiktoken
    path: /tmp/tokenizers/original/tokenizer.model

profiling:
  run: true

checkpoint:
  dump:
    every: 100
    keep: 3
  eval:
    every: 100
    keep: -1

logging:
  freq: 1

eval:
  harness:
    tasks:
      - hellaswag
      - piqa
      - winogrande
      - arc_easy
      - arc_challenge
      - commonsense_qa
      - task: copa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
      - mmlu
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
      # - coqa
      # - task: nq_open
      #   num_fewshot: 5
      # - triviaqa
  validation:
    max_steps: 1000
  generator:
    max_tokens: 16384
    dtype: bf16
