# Example GPT2 config ~420M
# Change "dump_dir" and "data" fields as needed

dump_dir: /is/cluster/fast/pmayilvahanan/lm_logs/lingua/gpt2_420M_fw_edu_8.4BT/
name: gpt2_420M
steps: 60000
probe_freq: null
seed: 777

optim:
  lr: 3e-3
  weight_decay: 0.033
  warmup: 5000
  lr_min_ratio: 0.000001
  clip: 1.0

distributed:
  fsdp_type: full_shard
  compile: true
  model_dtype: bf16
  matmul_allow_tf32: false
  selective_activation_checkpointing: false
  tp_size: 1

model:
  # ~420M parameters approximate
  dim: 1024
  n_layers: 29
  n_heads: 16
  n_positions: 2048
  vocab_size: 50257
  norm_eps: 1e-5
  # GPT2 architecture might also need a different norm_eps or other fields

data:
  root_dir: /fast/smallick/datasets/
  sources:
      fineweb_edu_100bt_shuffled: 1.0
  batch_size: 24
  prefetch_size: 1024
  seq_len: 2048
  n_views: 2
  load_async: true
  add_bos: true
  add_eos: true
  tokenizer:
    name: gpt2
    path: tmp/tokenizers/

profiling:
  run: true
  mem_warmup: 0
  mem_steps: 4
  profile_warmup: 100
  profile_steps: 4

checkpoint:
  dump:
    every: 500
    keep: 3
  eval:
    every: 500
    keep: -1

logging:
  freq: 1

eval:
  harness:
    compute_loss: true
    tasks:
      - hellaswag
      - piqa
      - winogrande
      - arc_easy
      - arc_challenge
      - commonsense_qa
      - openbookqa
      - task: copa
        dataset_kwargs:
          trust_remote_code: true
      - winogrande
      - mmlu
      - task: social_iqa
        dataset_kwargs:
          trust_remote_code: true
  validation:
    use_val_from_train_src: false
    max_steps: 5000
    root_dir: /fast/smallick/datasets/
    sources:
      - c4_shuffled
      - pile_uc_shuffled
      - fineweb_edu_100bt_shuffled
      - refineweb_shuffled
      - slimpajama_shuffled
  generator:
    max_tokens: 16384
    dtype: bf16